package eu.eyan.util.swing

import javax.swing.JTree
import eu.eyan.util.swing.JComponentPlus.JComponentImplicit

object JTreePlus {
  implicit class JTreeImplicit[TYPE <: JTree](jTree: TYPE) extends JComponentImplicit(jTree){
//    addSelectionInterval(int, int)
//    addSelectionPath(TreePath)
//    addSelectionPaths(TreePath[])
//    addSelectionRow(int)
//    addSelectionRows(int[])
//    addTreeExpansionListener(TreeExpansionListener)
//    addTreeSelectionListener(TreeSelectionListener)
//    addTreeWillExpandListener(TreeWillExpandListener)
//    cancelEditing()
//    clearSelection()
//    collapsePath(TreePath)
//    collapseRow(int)
//    convertValueToText(Object, boolean, boolean, boolean, int, boolean)
//    expandPath(TreePath)
//    expandRow(int)
//    fireTreeCollapsed(TreePath)
//    fireTreeExpanded(TreePath)
//    fireTreeWillCollapse(TreePath)
//    fireTreeWillExpand(TreePath)
//    makeVisible(TreePath)
//    removeSelectionInterval(int, int)
//    removeSelectionPath(TreePath)
//    removeSelectionPaths(TreePath[])
//    removeSelectionRow(int)
//    removeSelectionRows(int[])
//    removeTreeExpansionListener(TreeExpansionListener)
//    removeTreeSelectionListener(TreeSelectionListener)
//    removeTreeWillExpandListener(TreeWillExpandListener)
//    scrollPathToVisible(TreePath)
//    scrollRowToVisible(int)
//    setAnchorSelectionPath(TreePath)
//    setCellEditor(TreeCellEditor)
//    setCellRenderer(TreeCellRenderer)
//    setDragEnabled(boolean)
//    setDropMode(DropMode)
//    setEditable(boolean)
//    setExpandsSelectedPaths(boolean)
//    setInvokesStopCellEditing(boolean)
//    setLargeModel(boolean)
//    setLeadSelectionPath(TreePath)
//    setModel(TreeModel)
//    setRootVisible(boolean)
//    setRowHeight(int)
//    setScrollsOnExpand(boolean)
//    setSelectionInterval(int, int)
//    setSelectionModel(TreeSelectionModel)
//    setSelectionPath(TreePath)
//    setSelectionPaths(TreePath[])
//    setSelectionRow(int)
//    setSelectionRows(int[])
//    setShowsRootHandles(boolean)
//    setToggleClickCount(int)
//    setUI(TreeUI)
//    setVisibleRowCount(int)
//    startEditingAtPath(TreePath)
//    stopEditing()
//    treeDidChange()
//    updateUI()    
  }
}